"""Plot results generated by ``benches/find_best_batch_size.py``."""

import argparse
import pickle
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.axes import Axes


def plot_tvd_vs_batch_size_for_different_samplers(
    filename: Path,
    savefile: Path,
) -> None:
    """Plot one subplot per sampler for TVD versus batch size."""

    with open(filename, "rb") as input_file:
        dict_sampler_batch_tvd: dict[str, dict[int, float]] = pickle.load(input_file)

    fig, axes = plt.subplots(4, 2, figsize=(10, 10))
    fig.subplots_adjust(wspace=0.3, hspace=1.0)

    index: int
    sampler_key: str
    batch_tvd: dict[int, float]
    for index, (sampler_key, batch_tvd) in enumerate(dict_sampler_batch_tvd.items()):
        ax: Axes = axes[index // 2, index % 2]
        batch_sizes = sorted(batch_tvd.keys())
        tvd_values = [batch_tvd[bs] for bs in batch_sizes]
        ax.plot(batch_sizes, tvd_values, marker="o")
        ax.set_ylim(0.0, 0.5)
        ax.set_xlabel("Batch Size")
        ax.set_ylabel("TVD")
        ax.set_title(f"Sampler: {sampler_key}")
        ax.set_xticks(batch_sizes)

    savefile.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(savefile)


def plot_tvd_vs_num_qubits_for_different_batch_sizes(
    filename: Path,
    savefile: Path,
) -> None:
    """Plot TVD versus the number of qubits for each batch size."""

    with open(filename, "rb") as input_file:
        dict_batch_num_tvd: dict[int, dict[int, float]] = pickle.load(input_file)

    fig, ax = plt.subplots(figsize=(8, 6))
    markers = ["o", "s", "^", "D", "v", "P", "*"]
    linestyles = ["-", "--", "-.", ":"]

    index: int
    batch_size: int
    for index, batch_size in enumerate(dict_batch_num_tvd.keys()):
        dict_num_tvd = dict_batch_num_tvd[batch_size]
        num_qubits = sorted(dict_num_tvd.keys())
        tvd_values = [dict_num_tvd[nq] for nq in num_qubits]
        ax.plot(
            num_qubits,
            tvd_values,
            marker=markers[index],
            linestyle=linestyles[index],
            label=f"Batch Size {batch_size}",
        )

    ax.legend()
    ax.set_xlabel("Number of Qubits")
    ax.set_ylabel("TVD")

    savefile.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(savefile)


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser for batch-size plots."""

    parser = argparse.ArgumentParser(description="Plot batch-size benchmark results.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    sampler_parser = subparsers.add_parser(
        "plot-sampler-batch",
        help="Plot TVD versus batch size for all sampler configurations",
    )
    sampler_parser.add_argument("--results", type=Path, required=True)
    sampler_parser.add_argument("--output", type=Path, required=True)

    num_qubit_parser = subparsers.add_parser(
        "plot-batch-num-qubits",
        help="Plot TVD versus the number of qubits for each batch size",
    )
    num_qubit_parser.add_argument("--results", type=Path, required=True)
    num_qubit_parser.add_argument("--output", type=Path, required=True)

    return parser


def main() -> None:
    """CLI entry point."""

    parser = build_parser()
    args = parser.parse_args()

    match args.command:
        case "plot-sampler-batch":
            plot_tvd_vs_batch_size_for_different_samplers(args.results, args.output)
        case "plot-batch-num-qubits":
            plot_tvd_vs_num_qubits_for_different_batch_sizes(
                args.results,
                args.output,
            )
        case command:
            raise ValueError(f"Unknown command: {command}")


if __name__ == "__main__":
    main()
