"""Plot results generated by ``benches/find_best_batch_size.py``."""

import pickle
from pathlib import Path
from typing import Annotated

import matplotlib.pyplot as plt
import typer
from matplotlib.axes import Axes
from matplotlib_config import PlotConfig, configure_matplotlib, get_latex_figsize

app = typer.Typer()
PLOT_DIR: Path = Path(__file__).resolve().parent
PLOT_CONFIG: PlotConfig = configure_matplotlib(PLOT_DIR / "plot_config.toml")


def plot_tvd_vs_batch_size_for_different_samplers(
    filename: Path,
    savefile: Path,
) -> None:
    """Plot one subplot per sampler for TVD versus batch size."""
    with open(filename, "rb") as input_file:
        dict_sampler_batch_tvd: dict[str, dict[int, float]] = pickle.load(input_file)

    figsize: tuple[float, float] = get_latex_figsize(
        PLOT_CONFIG,
        width="text",
        fraction=0.95,
        height_ratio=1.25,
    )
    fig, axes = plt.subplots(4, 2, figsize=figsize)

    for index, (sampler_key, batch_tvd) in enumerate(dict_sampler_batch_tvd.items()):
        ax: Axes = axes[index // 2, index % 2]
        batch_sizes = sorted(batch_tvd.keys())
        tvd_values = [batch_tvd[bs] for bs in batch_sizes]
        ax.plot(batch_sizes, tvd_values, marker="o")
        ax.set_ylim(0.0, 0.5)
        ax.set_xlabel("Batch Size")
        ax.set_ylabel("TVD")
        ax.set_title(f"Sampler: {sampler_key}")
        ax.set_xticks(batch_sizes)

    savefile.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(savefile)


def plot_tvd_vs_num_qubits_for_different_batch_sizes(
    filename: Path,
    savefile: Path,
) -> None:
    """Plot TVD versus the number of qubits for each batch size."""
    with open(filename, "rb") as input_file:
        dict_batch_num_tvd: dict[int, dict[int, float]] = pickle.load(input_file)

    figsize: tuple[float, float] = get_latex_figsize(
        PLOT_CONFIG,
        width="column",
        fraction=0.95,
        height_ratio=0.75,
    )
    fig, ax = plt.subplots(figsize=figsize)
    markers = ["o", "s", "^", "D", "v", "P", "*"]
    linestyles = ["-", "--", "-.", ":"]

    for index, batch_size in enumerate(dict_batch_num_tvd.keys()):
        dict_num_tvd = dict_batch_num_tvd[batch_size]
        num_qubits = sorted(dict_num_tvd.keys())
        tvd_values = [dict_num_tvd[nq] for nq in num_qubits]
        ax.plot(
            num_qubits,
            tvd_values,
            marker=markers[index],
            linestyle=linestyles[index],
            label=f"Batch Size {batch_size}",
        )

    ax.legend()
    ax.set_xlabel("Number of Qubits")
    ax.set_ylabel("TVD")

    savefile.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(savefile)


@app.command()
def plot_sampler_batch(
    results: Annotated[Path, typer.Argument(help="Pickle results file")],
    output: Annotated[Path, typer.Argument(help="Output plot file path")],
) -> None:
    """Plot TVD versus batch size for all sampler configurations."""
    plot_tvd_vs_batch_size_for_different_samplers(results, output)


@app.command()
def plot_batch_num_qubits(
    results: Annotated[Path, typer.Argument(help="Pickle results file")],
    output: Annotated[Path, typer.Argument(help="Output plot file path")],
) -> None:
    """Plot TVD versus the number of qubits for each batch size."""
    plot_tvd_vs_num_qubits_for_different_batch_sizes(results, output)


if __name__ == "__main__":
    app()
