"""Plot results generated by ``benches/find_best_batch_size.py``."""

from pathlib import Path
from typing import Annotated

import matplotlib.pyplot as plt
import numpy as np
import typer
from matplotlib.axes import Axes
from matplotlib_config import get_latex_figsize, plot_context

from qft_dynamic.experiment_data import (
    ExperimentDataset,
    LogicalCountsGroup,
    MetadataValue,
)
from qft_dynamic.tools.data_process import calc_tvd

app = typer.Typer()
PLOT_DIR: Path = Path(__file__).resolve().parent
PLOT_CONFIG_PATH: Path = PLOT_DIR / "plot_config.toml"


def _integer_group_attribute(group: LogicalCountsGroup, name: str) -> int:
    """Read a required integer group attribute."""

    value: MetadataValue | None = group.attributes.get(name)
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"group {group.name!r} requires integer {name!r}")
    return value


def _ideal_probabilities(dataset: ExperimentDataset) -> dict[int, float]:
    """Build the ideal distribution for a supported input-state dataset."""

    input_state: MetadataValue | None = dataset.attributes.get("input_state")
    if input_state == "circular":
        return {state << (dataset.num_qubits - 2): 0.25 for state in range(4)}
    if input_state == "ghz":
        num_states: int = 1 << dataset.num_qubits
        return {
            state: float((1.0 + np.cos(2.0 * np.pi * state / num_states)) / num_states)
            for state in range(num_states)
        }
    raise ValueError(f"unsupported input_state={input_state!r}")


def _noise_name(group: LogicalCountsGroup) -> str:
    """Build a stable label from one group's noise toggles."""

    values: list[bool] = []
    for name in ("gate_error", "readout_error", "thermal_relaxation"):
        value: MetadataValue | None = group.attributes.get(name)
        if not isinstance(value, bool):
            raise ValueError(f"group {group.name!r} requires boolean {name!r}")
        values.append(value)
    return f"g{int(values[0])}-r{int(values[1])}-t{int(values[2])}"


def plot_tvd_vs_batch_size_for_different_samplers(
    filename: Path,
    savefile: Path,
) -> None:
    """Plot one subplot per noise configuration from a count dataset."""

    dataset: ExperimentDataset = ExperimentDataset.load(filename)
    ideal_probabilities: dict[int, float] = _ideal_probabilities(dataset)
    dict_sampler_batch_tvd: dict[str, dict[int, float]] = {}
    for group in dataset.groups:
        noise_name: str = _noise_name(group)
        batch_size: int = _integer_group_attribute(group, "batch_size")
        dict_sampler_batch_tvd.setdefault(noise_name, {})[batch_size] = calc_tvd(
            ideal_probabilities,
            group.runs[0].counts,
        )

    with plot_context(PLOT_CONFIG_PATH, palette="nature") as config:
        figsize: tuple[float, float] = get_latex_figsize(
            config,
            width="text",
            fraction=0.95,
            height_ratio=1.25,
        )
        fig, axes = plt.subplots(4, 2, figsize=figsize)

        for index, (sampler_key, batch_tvd) in enumerate(
            dict_sampler_batch_tvd.items()
        ):
            ax: Axes = axes[index // 2, index % 2]
            batch_sizes = sorted(batch_tvd.keys())
            tvd_values = [batch_tvd[bs] for bs in batch_sizes]
            ax.plot(batch_sizes, tvd_values, marker="o")
            ax.set_ylim(0.0, 0.5)
            ax.set_xlabel("Batch Size")
            ax.set_ylabel("TVD")
            ax.set_title(f"Sampler: {sampler_key}")
            ax.set_xticks(batch_sizes)

        savefile.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(savefile)
        plt.close(fig)


def plot_tvd_vs_num_qubits_for_different_batch_sizes(
    filename: Path,
    savefile: Path,
) -> None:
    """Plot TVD versus qubit count from a directory of count datasets."""

    dict_batch_num_tvd: dict[int, dict[int, float]] = {}
    for dataset_path in sorted(filename.glob("*.json")):
        dataset: ExperimentDataset = ExperimentDataset.load(dataset_path)
        ideal_probabilities: dict[int, float] = _ideal_probabilities(dataset)
        for group in dataset.groups:
            batch_size: int = _integer_group_attribute(group, "batch_size")
            dict_batch_num_tvd.setdefault(batch_size, {})[dataset.num_qubits] = (
                calc_tvd(ideal_probabilities, group.runs[0].counts)
            )

    with plot_context(PLOT_CONFIG_PATH, palette="nature") as config:
        figsize: tuple[float, float] = get_latex_figsize(
            config,
            width="column",
            fraction=0.95,
            height_ratio=0.75,
        )
        fig, ax = plt.subplots(figsize=figsize)
        markers = ["o", "s", "^", "D", "v", "P", "*"]
        linestyles = ["-", "--", "-.", ":"]

        for index, batch_size in enumerate(dict_batch_num_tvd.keys()):
            dict_num_tvd = dict_batch_num_tvd[batch_size]
            num_qubits = sorted(dict_num_tvd.keys())
            tvd_values = [dict_num_tvd[nq] for nq in num_qubits]
            ax.plot(
                num_qubits,
                tvd_values,
                marker=markers[index],
                linestyle=linestyles[index],
                label=f"Batch Size {batch_size}",
            )

        ax.legend()
        ax.set_xlabel("Number of Qubits")
        ax.set_ylabel("TVD")

        savefile.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(savefile)
        plt.close(fig)


@app.command()
def plot_sampler_batch(
    results: Annotated[Path, typer.Argument(help="Counter ExperimentDataset JSON")],
    output: Annotated[Path, typer.Argument(help="Output plot file path")],
) -> None:
    """Plot TVD versus batch size for all sampler configurations."""
    plot_tvd_vs_batch_size_for_different_samplers(results, output)


@app.command()
def plot_batch_num_qubits(
    results: Annotated[
        Path, typer.Argument(help="Counter ExperimentDataset directory")
    ],
    output: Annotated[Path, typer.Argument(help="Output plot file path")],
) -> None:
    """Plot TVD versus the number of qubits for each batch size."""
    plot_tvd_vs_num_qubits_for_different_batch_sizes(results, output)


if __name__ == "__main__":
    app()
